import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from './components/Navbar'
import Home from './sections/home'
import About from './sections/about'
import Footer from './components/footer'
import styles from '../styles/Home.module.css'

const Index: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <Home />
        <About />

      </main>

      <Footer />
    </div>
  )
}

export default Index